"""
Incident model
==============

Represents a single IT incident/ticket in the system.

Lifecycle: OPEN -> IN_PROGRESS -> RESOLVED -> CLOSED
Soft-delete: incidents are never physically deleted (audit trail).
"""

from datetime import datetime
from enum import Enum

from sqlalchemy import (
    Column, Integer, String, Text, DateTime, Boolean,
    ForeignKey, Enum as SQLEnum, Index,
)
from sqlalchemy.orm import relationship

from app.extensions import db


# ============================================================
# ENUMS
# ============================================================

class IncidentSeverity(str, Enum):
    """Business impact of the incident."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(str, Enum):
    """Current state in the incident lifecycle."""
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class IncidentCategory(str, Enum):
    """High-level classification matching SystemMonitor subsystems."""
    CPU = "CPU"
    MEMORY = "MEMORY"
    DISK = "DISK"
    NETWORK = "NETWORK"
    APPLICATION = "APPLICATION"
    OTHER = "OTHER"


class IncidentSource(str, Enum):
    """How the incident was created."""
    MANUAL = "MANUAL"          # Reported by a human via API
    AUTOMATED = "AUTOMATED"    # Created by the alerting engine


# Default SLA targets per severity (in minutes) — used by escalation logic later
DEFAULT_SLA_MINUTES = {
    IncidentSeverity.CRITICAL: 60,      # 1h
    IncidentSeverity.HIGH:     240,     # 4h
    IncidentSeverity.MEDIUM:   1440,    # 24h
    IncidentSeverity.LOW:      4320,    # 72h
}


# ============================================================
# MODEL
# ============================================================

class Incident(db.Model):
    """
    An IT incident reported by a user or generated by the alerting engine.
    """

    __tablename__ = "incidents"

    # --- Primary key ---
    id = Column(Integer, primary_key=True)

    # --- Content ---
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)

    # --- Classification (Enums for data integrity) ---
    severity = Column(
        SQLEnum(IncidentSeverity, name="incident_severity"),
        nullable=False,
        default=IncidentSeverity.MEDIUM,
    )
    status = Column(
        SQLEnum(IncidentStatus, name="incident_status"),
        nullable=False,
        default=IncidentStatus.OPEN,
    )
    category = Column(
        SQLEnum(IncidentCategory, name="incident_category"),
        nullable=False,
        default=IncidentCategory.OTHER,
    )
    source = Column(
        SQLEnum(IncidentSource, name="incident_source"),
        nullable=False,
        default=IncidentSource.MANUAL,
    )

    # --- Relationships to User ---
    reported_by_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    assigned_to_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    reported_by = relationship("User", foreign_keys=[reported_by_id])
    assigned_to = relationship("User", foreign_keys=[assigned_to_id])

    # --- Timestamps (UTC) ---
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )
    resolved_at = Column(DateTime, nullable=True)

    # --- SLA target (in minutes from creation) ---
    sla_minutes = Column(Integer, nullable=True)

    # --- Soft delete ---
    is_deleted = Column(Boolean, nullable=False, default=False)

    # --- Indexes for common query patterns ---
    __table_args__ = (
        Index("ix_incidents_status_severity", "status", "severity"),
        Index("ix_incidents_category", "category"),
        Index("ix_incidents_created_at", "created_at"),
    )

    # ============================================================
    # BUSINESS LOGIC
    # ============================================================

    def mark_resolved(self) -> None:
        """Transition the incident to RESOLVED and stamp resolved_at."""
        self.status = IncidentStatus.RESOLVED
        self.resolved_at = datetime.utcnow()

    def assign_to(self, user_id: int) -> None:
        """Assign the incident to a user (typically a support technician)."""
        self.assigned_to_id = user_id
        if self.status == IncidentStatus.OPEN:
            self.status = IncidentStatus.IN_PROGRESS

    def apply_default_sla(self) -> None:
        """Set sla_minutes based on severity, if not already set."""
        if self.sla_minutes is None:
            self.sla_minutes = DEFAULT_SLA_MINUTES.get(self.severity)

    def is_sla_breached(self) -> bool:
        """Return True if the incident is open past its SLA target."""
        if self.sla_minutes is None or self.status in (
            IncidentStatus.RESOLVED, IncidentStatus.CLOSED,
        ):
            return False
        elapsed = (datetime.utcnow() - self.created_at).total_seconds() / 60
        return elapsed > self.sla_minutes

    # ============================================================
    # SERIALIZATION (kept simple; Marshmallow does the heavy lifting later)
    # ============================================================

    def to_dict(self) -> dict:
        """Lightweight dict representation (mainly for debugging)."""
        return {
            "id": self.id,
            "title": self.title,
            "severity": self.severity.value,
            "status": self.status.value,
            "category": self.category.value,
            "source": self.source.value,
            "reported_by_id": self.reported_by_id,
            "assigned_to_id": self.assigned_to_id,
            "created_at": self.created_at.isoformat() + "Z" if self.created_at else None,
            "updated_at": self.updated_at.isoformat() + "Z" if self.updated_at else None,
            "resolved_at": self.resolved_at.isoformat() + "Z" if self.resolved_at else None,
            "sla_minutes": self.sla_minutes,
            "sla_breached": self.is_sla_breached(),
            "is_deleted": self.is_deleted,
        }

    def __repr__(self) -> str:
        return f"<Incident id={self.id} severity={self.severity.value} status={self.status.value}>"